PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_VBELN.

MODULE %_S_MATNR.

MODULE %_S_CHARG.

MODULE %_S_KUNNR.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD  S_VBELN-LOW.
  FIELD  S_VBELN-HIGH.
  MODULE %_S_VBELN.
ENDCHAIN.

CHAIN.
  FIELD  S_MATNR-LOW.
  FIELD  S_MATNR-HIGH.
  MODULE %_S_MATNR.
ENDCHAIN.

CHAIN.
  FIELD  S_CHARG-LOW.
  FIELD  S_CHARG-HIGH.
  MODULE %_S_CHARG.
ENDCHAIN.

CHAIN.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  MODULE %_S_KUNNR.
ENDCHAIN.

FIELD !P_FOR MODULE %_P_FOR .

CHAIN.
  FIELD  S_VBELN-LOW.
  FIELD  S_VBELN-HIGH.
  FIELD  S_MATNR-LOW.
  FIELD  S_MATNR-HIGH.
  FIELD  S_CHARG-LOW.
  FIELD  S_CHARG-HIGH.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  FIELD P_FOR .
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.