PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_DATET.

MODULE %_S_CITYF.

MODULE %_S_CITYT.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD P_RADIO1.
  FIELD P_RADIO2.
    MODULE %_RADIOBUTTON_GROUP_RAD1                          .
ENDCHAIN.

FIELD !P_ID MODULE %_P_ID .

FIELD !P_SURNAM MODULE %_P_SURNAM .

FIELD !P_NAME MODULE %_P_NAME .

FIELD !P_DATEB MODULE %_P_DATEB .

FIELD !P_CITY MODULE %_P_CITY .

FIELD !P_COUNT MODULE %_P_COUNT .

FIELD !P_LANG MODULE %_P_LANG .

FIELD !P_DATE MODULE %_P_DATE .

FIELD !P_HOUR MODULE %_P_HOUR .

FIELD !P_ID_D MODULE %_P_ID_D .

FIELD !P_IDP1 MODULE %_P_IDP1 .

FIELD !P_IDP2 MODULE %_P_IDP2 .

FIELD !P_IDP3 MODULE %_P_IDP3 .

FIELD !P_CITF MODULE %_P_CITF .

FIELD !P_COUNF MODULE %_P_COUNF .

FIELD !P_CITT MODULE %_P_CITT .

FIELD !P_COUNTO MODULE %_P_COUNTO .

FIELD !P_KMS MODULE %_P_KMS .

FIELD !P_KMS_U MODULE %_P_KMS_U .

FIELD !P_DUR MODULE %_P_DUR .

FIELD !P_TOLL MODULE %_P_TOLL .

FIELD !P_GAZOL MODULE %_P_GAZOL .

FIELD !P_UNIT MODULE %_P_UNIT .


CHAIN.
  FIELD P_ID .
  FIELD P_SURNAM .
  FIELD P_NAME .
  FIELD P_DATEB .
  FIELD P_CITY .
  FIELD P_COUNT .
  FIELD P_LANG .
  FIELD P_DATE .
  FIELD P_HOUR .
  FIELD P_ID_D .
  FIELD P_IDP1 .
  FIELD P_IDP2 .
  FIELD P_IDP3 .
  FIELD P_CITF .
  FIELD P_COUNF .
  FIELD P_CITT .
  FIELD P_COUNTO .
  FIELD P_KMS .
  FIELD P_KMS_U .
  FIELD P_DUR .
  FIELD P_TOLL .
  FIELD P_GAZOL .
  FIELD P_UNIT .
    MODULE %_BLOCK_1000002.
ENDCHAIN.

CHAIN.
  FIELD  S_DATET-LOW.
  FIELD  S_DATET-HIGH.
  MODULE %_S_DATET.
ENDCHAIN.

CHAIN.
  FIELD  S_CITYF-LOW.
  FIELD  S_CITYF-HIGH.
  MODULE %_S_CITYF.
ENDCHAIN.

CHAIN.
  FIELD  S_CITYT-LOW.
  FIELD  S_CITYT-HIGH.
  MODULE %_S_CITYT.
ENDCHAIN.


CHAIN.
  FIELD  S_DATET-LOW.
  FIELD  S_DATET-HIGH.
  FIELD  S_CITYF-LOW.
  FIELD  S_CITYF-HIGH.
  FIELD  S_CITYT-LOW.
  FIELD  S_CITYT-HIGH.
    MODULE %_BLOCK_1000028.
ENDCHAIN.


CHAIN.
  FIELD P_RADIO1.
  FIELD P_RADIO2.
  FIELD P_ID .
  FIELD P_SURNAM .
  FIELD P_NAME .
  FIELD P_DATEB .
  FIELD P_CITY .
  FIELD P_COUNT .
  FIELD P_LANG .
  FIELD P_DATE .
  FIELD P_HOUR .
  FIELD P_ID_D .
  FIELD P_IDP1 .
  FIELD P_IDP2 .
  FIELD P_IDP3 .
  FIELD P_CITF .
  FIELD P_COUNF .
  FIELD P_CITT .
  FIELD P_COUNTO .
  FIELD P_KMS .
  FIELD P_KMS_U .
  FIELD P_DUR .
  FIELD P_TOLL .
  FIELD P_GAZOL .
  FIELD P_UNIT .
  FIELD  S_DATET-LOW.
  FIELD  S_DATET-HIGH.
  FIELD  S_CITYF-LOW.
  FIELD  S_CITYF-HIGH.
  FIELD  S_CITYT-LOW.
  FIELD  S_CITYT-HIGH.
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD P_RADIO1.
  FIELD P_RADIO2.
  FIELD P_ID .
  FIELD P_SURNAM .
  FIELD P_NAME .
  FIELD P_DATEB .
  FIELD P_CITY .
  FIELD P_COUNT .
  FIELD P_LANG .
  FIELD P_DATE .
  FIELD P_HOUR .
  FIELD P_ID_D .
  FIELD P_IDP1 .
  FIELD P_IDP2 .
  FIELD P_IDP3 .
  FIELD P_CITF .
  FIELD P_COUNF .
  FIELD P_CITT .
  FIELD P_COUNTO .
  FIELD P_KMS .
  FIELD P_KMS_U .
  FIELD P_DUR .
  FIELD P_TOLL .
  FIELD P_GAZOL .
  FIELD P_UNIT .
  FIELD  S_DATET-LOW.
  FIELD  S_DATET-HIGH.
  FIELD  S_CITYF-LOW.
  FIELD  S_CITYF-HIGH.
  FIELD  S_CITYT-LOW.
  FIELD  S_CITYT-HIGH.
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.