PROCESS BEFORE OUTPUT.

MODULE %_INIT_PBO.

MODULE %_PBO_REPORT.

MODULE %_PF_STATUS.

MODULE %_S_VBELN.

MODULE %_S_AUART.

MODULE %_S_VKORG.

MODULE %_S_VTWEG.

MODULE %_S_SPART.

MODULE %_S_MATNR.

MODULE %_S_PLANT.

MODULE %_S_KUNNR.

MODULE %_S_ERDAT.

MODULE %_END_OF_PBO.

PROCESS AFTER INPUT.

  MODULE %_BACK AT EXIT-COMMAND.

  MODULE %_INIT_PAI.

CHAIN.
  FIELD P_CREA  .
  FIELD P_ALV   .
    MODULE %_RADIOBUTTON_GROUP_RB1                           .
ENDCHAIN.

CHAIN.
  FIELD P_RAD1  .
  FIELD P_RAD2  .
    MODULE %_RADIOBUTTON_GROUP_RB2                           .
ENDCHAIN.

FIELD !P_FNAME MODULE %_P_FNAME .

FIELD !P_LPATH MODULE %_P_LPATH .

FIELD !P_LNAME MODULE %_P_LNAME .

FIELD !P_ARCH MODULE %_P_ARCH .

CHAIN.
  FIELD P_RAD3  .
  FIELD P_RAD4  .
    MODULE %_RADIOBUTTON_GROUP_RB3                           .
ENDCHAIN.


CHAIN.
  FIELD P_RAD1  .
  FIELD P_RAD2  .
  FIELD P_FNAME .
  FIELD P_LPATH .
  FIELD P_LNAME .
  FIELD P_ARCH .
  FIELD P_RAD3  .
  FIELD P_RAD4  .
    MODULE %_BLOCK_1000002.
ENDCHAIN.

FIELD !P_ERNAM MODULE %_P_ERNAM .

CHAIN.
  FIELD  S_VBELN-LOW.
  FIELD  S_VBELN-HIGH.
  MODULE %_S_VBELN.
ENDCHAIN.

CHAIN.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  MODULE %_S_AUART.
ENDCHAIN.

CHAIN.
  FIELD  S_VKORG-LOW.
  FIELD  S_VKORG-HIGH.
  MODULE %_S_VKORG.
ENDCHAIN.

CHAIN.
  FIELD  S_VTWEG-LOW.
  FIELD  S_VTWEG-HIGH.
  MODULE %_S_VTWEG.
ENDCHAIN.

CHAIN.
  FIELD  S_SPART-LOW.
  FIELD  S_SPART-HIGH.
  MODULE %_S_SPART.
ENDCHAIN.

CHAIN.
  FIELD  S_MATNR-LOW.
  FIELD  S_MATNR-HIGH.
  MODULE %_S_MATNR.
ENDCHAIN.

CHAIN.
  FIELD  S_PLANT-LOW.
  FIELD  S_PLANT-HIGH.
  MODULE %_S_PLANT.
ENDCHAIN.

CHAIN.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  MODULE %_S_KUNNR.
ENDCHAIN.

CHAIN.
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
  MODULE %_S_ERDAT.
ENDCHAIN.


CHAIN.
  FIELD P_ERNAM .
  FIELD  S_VBELN-LOW.
  FIELD  S_VBELN-HIGH.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  FIELD  S_VKORG-LOW.
  FIELD  S_VKORG-HIGH.
  FIELD  S_VTWEG-LOW.
  FIELD  S_VTWEG-HIGH.
  FIELD  S_SPART-LOW.
  FIELD  S_SPART-HIGH.
  FIELD  S_MATNR-LOW.
  FIELD  S_MATNR-HIGH.
  FIELD  S_PLANT-LOW.
  FIELD  S_PLANT-HIGH.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
    MODULE %_BLOCK_1000015.
ENDCHAIN.


CHAIN.
  FIELD P_CREA  .
  FIELD P_ALV   .
  FIELD P_RAD1  .
  FIELD P_RAD2  .
  FIELD P_FNAME .
  FIELD P_LPATH .
  FIELD P_LNAME .
  FIELD P_ARCH .
  FIELD P_RAD3  .
  FIELD P_RAD4  .
  FIELD P_ERNAM .
  FIELD  S_VBELN-LOW.
  FIELD  S_VBELN-HIGH.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  FIELD  S_VKORG-LOW.
  FIELD  S_VKORG-HIGH.
  FIELD  S_VTWEG-LOW.
  FIELD  S_VTWEG-HIGH.
  FIELD  S_SPART-LOW.
  FIELD  S_SPART-HIGH.
  FIELD  S_MATNR-LOW.
  FIELD  S_MATNR-HIGH.
  FIELD  S_PLANT-LOW.
  FIELD  S_PLANT-HIGH.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
    MODULE %_BLOCK_1000000.
ENDCHAIN.

CHAIN.
  FIELD P_CREA  .
  FIELD P_ALV   .
  FIELD P_RAD1  .
  FIELD P_RAD2  .
  FIELD P_FNAME .
  FIELD P_LPATH .
  FIELD P_LNAME .
  FIELD P_ARCH .
  FIELD P_RAD3  .
  FIELD P_RAD4  .
  FIELD P_ERNAM .
  FIELD  S_VBELN-LOW.
  FIELD  S_VBELN-HIGH.
  FIELD  S_AUART-LOW.
  FIELD  S_AUART-HIGH.
  FIELD  S_VKORG-LOW.
  FIELD  S_VKORG-HIGH.
  FIELD  S_VTWEG-LOW.
  FIELD  S_VTWEG-HIGH.
  FIELD  S_SPART-LOW.
  FIELD  S_SPART-HIGH.
  FIELD  S_MATNR-LOW.
  FIELD  S_MATNR-HIGH.
  FIELD  S_PLANT-LOW.
  FIELD  S_PLANT-HIGH.
  FIELD  S_KUNNR-LOW.
  FIELD  S_KUNNR-HIGH.
  FIELD  S_ERDAT-LOW.
  FIELD  S_ERDAT-HIGH.
  MODULE %_END_OF_SCREEN.
  MODULE %_OK_CODE_1000.
ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD P_FNAME MODULE %_P_FNAME_VAL .